# Generated by Django 6.0.2 on 2026-02-13 23:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movilnet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(max_length=50, verbose_name='Tipo de Movimiento')),
                ('categoria_movimiento', models.CharField(max_length=50, verbose_name='Categoría de Movimiento')),
            ],
            options={
                'verbose_name': 'Tipo de Inventario',
                'verbose_name_plural': 'Tipos de Inventario',
                'ordering': ['tipo_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cotizacion', models.DateField(verbose_name='Fecha de Cotización')),
                ('validez_dias', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Validez (días)')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='movilnet.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_cotizacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='movilnet.cotizacion', verbose_name='Cotización')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_cotizacion', to='movilnet.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Cotización',
                'verbose_name_plural': 'Detalles de Cotización',
            },
        ),
        migrations.CreateModel(
            name='NotaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_entrega', models.CharField(max_length=50, unique=True, verbose_name='Número de Entrega')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_entrega', to='movilnet.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Nota de Entrega',
                'verbose_name_plural': 'Notas de Entrega',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='DetalleNotaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_nota_entrega', to='movilnet.producto', verbose_name='Producto')),
                ('nota_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='movilnet.notaentrega', verbose_name='Nota de Entrega')),
            ],
            options={
                'verbose_name': 'Detalle de Nota de Entrega',
                'verbose_name_plural': 'Detalles de Nota de Entrega',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=50, unique=True, verbose_name='Número de Orden')),
                ('fecha_orden', models.DateField(verbose_name='Fecha de Orden')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='movilnet.cotizacion', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha_orden'],
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad Solicitada')),
                ('cantidad_recibida', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Recibida')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_orden_compra', to='movilnet.producto', verbose_name='Producto')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='movilnet.ordencompra', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'Detalle de Orden de Compra',
                'verbose_name_plural': 'Detalles de Orden de Compra',
            },
        ),
        migrations.CreateModel(
            name='PerfilEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('empleado', 'Empleado')], default='empleado', max_length=20, verbose_name='Rol')),
                ('animal_favorito', models.CharField(max_length=100, verbose_name='Animal Favorito')),
                ('color_favorito', models.CharField(max_length=100, verbose_name='Color Favorito')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Empleado',
                'verbose_name_plural': 'Perfiles de Empleados',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla_afectada', models.CharField(max_length=100, verbose_name='Tabla Afectada')),
                ('accion_realizada', models.CharField(max_length=50, verbose_name='Acción Realizada')),
                ('cod_registro_afectado', models.IntegerField(verbose_name='Código Registro Afectado')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to='movilnet.perfilempleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Bitácora',
                'verbose_name_plural': 'Bitácoras',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Movimiento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='movilnet.producto', verbose_name='Producto')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='movilnet.perfilempleado', verbose_name='Empleado')),
                ('tipo_inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='movilnet.tipoinventario', verbose_name='Tipo de Inventario')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha_movimiento'],
            },
        ),
    ]
