# Generated by Django 6.0.2 on 2026-04-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movilnet', '0004_detallecotizacion_precio_ordencompra_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoinventario',
            name='categoria_movimiento',
            field=models.CharField(max_length=50, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tipoinventario',
            name='direccion',
            field=models.CharField(choices=[('ENTRADA', 'Entrada (suma stock)'), ('SALIDA', 'Salida (resta stock)')], help_text='ENTRADA suma unidades al stock. SALIDA las resta.', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='tipoinventario',
            name='tipo_movimiento',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
